name: "Run Unit Tests"
description: "Runs the Minecraft Unit Tests"

inputs:
  store:
    type: boolean
    description: 'Stores the results and reports.'
    default: true

runs:
  using: "composite"
  steps:
    - name: Run Unit Tests
      shell: bash
      run: |
        chmod +x ./gradlew
        ./gradlew check

    - name: Store Reports
      if: ${{ inputs.store == true }}
      uses: actions/upload-artifact@v4
      with:
        name: reports
        path: |
          **/build/reports/
          **/build/test-results/
