name: "Pre Testing"
description: "Prepare the environment for testing"

inputs:
  java:
    required: false
    type: number
    description: 'Java version to use for testing. Defaults to 22.'
    default: 22

  java_dist:
    required: false
    type: string
    description: 'Java distribution to use for testing. Defaults to "adopt".'
    default: 'adopt'

  os:
    required: false,
    type: string
    description: 'Operating system to use for testing. Defaults to "ubuntu-latest".'
    default: 'ubuntu-latest'

runs:
  using: "composite"
  steps:
    - name: Validate Gradle Wrapper
      uses: gradle/wrapper-validation-action@v1

    - name: Setup JDK ${{ inputs.java }}
      uses: actions/setup-java@v4
      with:
        distribution: 'adopt'
        java-version: ${{ inputs.java }}

    - name: Make Gradle Wrapper Executable
      if: ${{ inputs.os != 'Windows' }}
      shell: bash
      run: chmod +x ./gradlew

    - name: Build Mod with Gradle
      shell: bash
      run: ./gradlew build
