# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defence
# against bad commits.

name: Build Check
on: [pull_request, push]

jobs:
  build:
    strategy:
      matrix:
        # Use these Java versions
        java: [
          21, # Minimum supported by Minecraft
          22  # Current Java LTS
        ]
        # Run on both Linux
        os:
          - ubuntu-latest

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Prepare Testing
        uses: ./.github/actions/prep
        with:
          java: ${{ matrix.java }}
          os: ${{ matrix.os }}

      - name: Run Test
        uses: ./.github/actions/run_test

      - name: Capture Build Artifacts
        if: ${{ runner.os == 'Linux' }} # Only upload artifacts built from latest java on one OS
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: build/libs/
