# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defence
# against bad commits.

name: Build Check
on: [pull_request, push]

jobs:
  build:
    strategy:
      matrix:
        # Use these Java versions
        java: [
          22  # Current Java LTS & minimum supported by Minecraft
        ]
        # Run on both Linux and Windows
        os:
          - ubuntu-latest
          - windows-latest

    runs-on: ${{ matrix.os }}
    steps:
      - name: Prepare Testing
        uses: ./.github/workflows/prep.yml
        with:
          java: ${{ matrix.java }}
          os: ${{ matrix.os }}

      - name: Capture Build Artifacts
        if: ${{ runner.os == 'Linux' && matrix.java == '22' }} # Only upload artifacts built from latest java on one OS
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: build/libs/
