name: Fabric Testing
on: [pull_request, push]

jobs:
  run:
    strategy:
        matrix:
          version:
            - {mc: 1.21.3, java: 21, loader: fabric}
    runs-on: ubuntu-latest

    steps:
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.version.java }}

      - name: Build mod
        run: ./gradlew build

      - name: Stage mod for test client
        run: |
          mkdir -p run/mods
          cp build/libs/.jar run/mods

      - name: Run MC test client
        uses: headlesshq/mc-runtime-test@3
        with:
          mc: ${{ matrix.minecraft_version }}
          modloader: ${{ matrix.version.loader }}
          regex: .*${{ matrix.version.loader }}.*
          mc-runtime-test: ${{ matrix.version.loader }}
          xvfb: false
          java: ${{ matrix.version.java }}
