name: Fabric Testing
on: [pull_request, push]

jobs:
  run:
    strategy:
      matrix:
        version:
          - {mc: 1.21.3, java: 22, loader: fabric}
        os:
          - ubuntu-latest
          - windows-latest

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Prepare Testing
        uses: ./.github/actions/prep
        with:
          java: ${{ matrix.version.java }}
          os: ubuntu-latest

      - name: Get jar name
        id: get_jar_name
        run: |
          run: echo "JAR_NAME=$( ./gradlew -q :getJarName )" >> $GITHUB_ENV

      - name: Stage mod for test client
        run: |
          mkdir -p run/mods
          cp build/libs/${{ env.JAR_NAME }}.jar run/mods

      - name: Run MC test client
        uses: headlesshq/mc-runtime-test@3.0.0
        with:
          mc: ${{ matrix.minecraft_version }}
          modloader: ${{ matrix.version.loader }}
          regex: .*${{ matrix.version.loader }}.*
          mc-runtime-test: ${{ matrix.version.loader }}
          xvfb: false
          java: ${{ matrix.version.java }}
